### ISSUE TITLE
Switch to TOML Configuration?

### ISSUE THREAD

**Issue by brianwyka** [Optum/sourcehawk#48]
```toml

config-locations = [
    "https://raw.githubusercontent.com/optum/sourcehawk-parent/.sourcehawk/config.toml"
]

[[file-protocols]]
repository-path = "lombok.config"
severity = "ERROR"

[[file-protocols.enforcers]]
enforcer = "STRING_PROPERTY_EQUALS"
name = "config.stopBubbling"
value = true

[[file-protocols.enforcers]]
enforcer = "string-property-equals"
name = "lombok.addLombokGeneratedAnnotation"
value = true
```
