### ISSUE TITLE
Support validation via a web service, like a function.

### ISSUE THREAD

**Issue by davidasnider** [Optum/sourcehawk#57]
Assuming I want to validate a particular yaml or json file against a schema. If I have a webservice that accepts a payload with the yaml/json, the web service returns a 2XX for succes and 4xx for failure, Sourcehawk could record the result appropriately.  This would open many doors for possible scans/validations.

**Comment by brianwyka** [comment]
I'll begin working on this @davidasnider.  The configuration will look something like this:

```yaml
file-protocols:
    - name: HTTP Function Validated
      repository-path: path/to/file.txt
      enforcers:
        - enforcer: .http.ContentHttpValidated
          url: http://function.in.cloud/validate
          connect-timeout: 200
          read-timeout: 2000
```
